In [4]:
import pandas as pd

df = pd.read_csv('../../data/raw/fake_job_postings.csv')
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  str
 2   location             17534 non-null  str
 3   department           6333 non-null   str
 4   salary_range         2868 non-null   str
 5   company_profile      14572 non-null  str
 6   description          17879 non-null  str
 7   requirements         15184 non-null  str
 8   benefits             10668 non-null  str
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  str
 13  required_experience  10830 non-null  str
 14  required_education   9775 non-null   str
 15  industry             12977 non-null  str
 16  function             11425 non-null  str
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), str(13)
memory usage: 2.5 MB

In [6]:
df['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

In [7]:
df.isnull().sum().sort_values(ascending=False)

salary_range           15012
department             11547
required_education      8105
benefits                7212
required_experience     7050
function                6455
industry                4903
employment_type         3471
company_profile         3308
requirements            2696
location                 346
description                1
title                      0
job_id                     0
telecommuting              0
has_questions              0
has_company_logo           0
fraudulent                 0
dtype: int64

In [8]:
df['text'] = (
    df['title'].fillna('') + ' ' +
    df['description'].fillna('') + ' ' +
    df['requirements'].fillna('')
)

In [9]:
import re

df['has_salary'] = df['salary_range'].notna().astype(int)

df['urgency_words'] = df['text'].str.count(
    r'\b(urgent|immediately|asap|earn \$)\b', flags=re.I
)

df['generic_email'] = df['text'].str.contains(
    r'@gmail|@yahoo|@hotmail', flags=re.I
).astype(int)

df['all_caps_ratio'] = df['text'].apply(
    lambda x: sum(1 for c in x if c.isupper()) / max(len(x), 1)
)

In [10]:
df['text_length'] = df['text'].apply(len)

In [11]:
df[['text', 'has_salary', 'urgency_words', 'generic_email', 'all_caps_ratio']].head()

,text,has_salary,urgency_words,generic_email,all_caps_ratio
0,"Marketing Intern Food52, a fast-growing, James...",0,0,0,0.024789
1,Customer Service - Cloud Video Production Orga...,0,0,0,0.025612
2,Commissioning Machinery Assistant (CMA) Our cl...,0,0,0,0.022172
3,Account Executive - Washington DC THE COMPANY:...,0,0,0,0.029774
4,Bill Review Manager JOB TITLE: Itemization Rev...,0,0,0,0.085292

In [12]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(
    df,
    test_size=0.2,
    stratify=df['fraudulent'],
    random_state=42
)

train, val = train_test_split(
    train,
    test_size=0.15,
    stratify=train['fraudulent'],
    random_state=42
)

In [13]:
train.to_csv('../../data/processed/train.csv', index=False)
val.to_csv('../../data/processed/val.csv', index=False)
test.to_csv('../../data/processed/test.csv', index=False)

OSError: Cannot save file into a non-existent directory: '..\..\data\processed'

In [14]:
train.to_csv('../../data/processed/train.csv', index=False)
val.to_csv('../../data/processed/val.csv', index=False)
test.to_csv('../../data/processed/test.csv', index=False)